### ISSUE TITLE
complete structure dataset download fail

### ISSUE THREAD

**Issue by barsur93** [Nanotekton/klifs_tools#1]
The execution of the full dataset of KLIFS structures with command:
`python ~/Software/klifs_tools/main.py download-all-klifs-structures klifs_data.csv structure_data/` 

fails at the structure HUMAN_EGFR_5x2a_altC_chainD_complex.pdb

I will try to find workaround but just reporting :)

[745, 790, 855] structure_data/Klifs_9533/HUMAN_EGFR_5x2a_altC_chainD_complex.pdb
  2%|█▏                                                   | 99/4362 [05:02<3:37:01,  3.05s/it]
Traceback (most recent call last):
  File "/home/bart/Software/klifs_tools/main.py", line 75, in <module>
    app()
  File "/home/bart/anaconda3/envs/klifs/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/bart/anaconda3/envs/klifs/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/bart/anaconda3/envs/klifs/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/bart/anaconda3/envs/klifs/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bart/anaconda3/envs/klifs/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bart/anaconda3/envs/klifs/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/bart/anaconda3/envs/klifs/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/bart/Software/klifs_tools/main.py", line 26, in download_all_klifs_structures
    subpocket_crd = get_subpocket_crd_and_insert_marks(subpocket_residues, pdb_path)
  File "/home/bart/Software/klifs_tools/klifs_tools.py", line 234, in get_subpocket_crd_and_insert_marks
    vector = read_ca_center(residues, pdblines)
  File "/home/bart/Software/klifs_tools/klifs_tools.py", line 167, in read_ca_center
    assert len(vectors)==len(residues), f'too many chains?, {residues}'
AssertionError: too many chains?, [745, 790, 855]

**Comment by Nanotekton** [comment]
Corrected. Now download takes about 1 h 30 min, resulting with something like 10k structures.
